spring:
  config:
    activate:
      on-profile: prod
welcomeMsg: Hello from prod
server.port: 5000
---
spring:
  config:
    activate:
      on-profile: test
welcomeMsg: Hello from Test
server.port: 4001

